// All notes request
export const REQUEST_NOTES_PENDING = 'REQUEST_NOTES_PENDING'
export const REQUEST_NOTES_SUCCESS = 'REQUEST_NOTES_SUCCESS'
export const REQUEST_NOTES_FAILED = 'REQUEST_NOTES_FAILED'

// users
export const GET_ERRORS = "GET_ERRORS"
export const USER_LOADING = "USER_LOADING"
export const SET_CURRENT_USER = "SET_CURRENT_USER"

// Account Pane
export const SET_ACCOUNT_PANE_OPEN = "SET_ACCOUNT_PANE_OPEN"

// Note status
export const GET_NOTE_STATUS = "GET_NOTE_STATUS"