// All notes request
export const REQUEST_NOTES_PENDING = 'REQUEST_NOTES_PENDING'
export const REQUEST_NOTES_SUCCESS = 'REQUEST_NOTES_SUCCESS'
export const REQUEST_NOTES_FAILED = 'REQUEST_NOTES_FAILED'

// Single note request
export const REQUEST_SINGLE_NOTE_PENDING = 'REQUEST_SINGLE_NOTE_PENDING'
export const REQUEST_SINGLE_NOTE_SUCCESS = 'REQUEST_SINGLE_NOTE_SUCCESS'
export const REQUEST_SINGLE_NOTE_FAILED = 'REQUEST_SINGLE_NOTE_FAILED'

// users
export const GET_ERRORS = "GET_ERRORS"
export const USER_LOADING = "USER_LOADING"
export const SET_CURRENT_USER = "SET_CURRENT_USER"