version: '3.7'

services:
    webapp-server:
      build:
        context: .
        dockerfile: Dockerfile
      image: easynotes-server-img
      container_name: easynotes-node-express
      volumes:
       - .:/usr/src/app
      ports:
        - "8080:8080"
      depends_on:
        - mongo
      environment:
        - MONGO_HOSTNAME=mongo
        - MONGO_PORT=27017
        - MONGO_DB=easy-notes
    mongo:
      image: mongo
      container_name: easynotes-mongodb
      ports:
        - "27017:27017"